version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:randomkey

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: curdsystem
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
